name Acme Plain
bg_1 {paleyellow_1}
bg_2 {paleyellow_2}
bg_3 {paleyellow_3}
ui_bg {paleyellow_1}
ui_hl {neutral_hl}
match_bg {yellow_2}ee
match_focus_bg {purple_2}aa
selection_bg {yellow_2}ee
gray {paleyellow_4}
badge_bg #444444
button_bg #444444
