type light
blank_bg {white}
popup_bg {white}
fg {black}
fg_dim {black}78
fg_faint {black}40
fg_ghost {black}20
match_fg {black}
match_focus_fg {black}
neutral_hl {black}10
badge_bg {purple_1}
badge_fg {white}
button_bg {purple_1}
button_fg {white}
