paleyellow_1	#ffffea
paleyellow_2	#f2f2dd
paleyellow_3	#eeeed9
paleyellow_4	#777770
gray_1	#f6f6f6
gray_2	#eeeeee
gray_3	#e8e8e8
gray_4	#888888
black	#000000
white	#ffffff
red_1	#bb5d5d
red_2	#dd8888
orange_1	#c78f67
orange_2	#f8dfc8
yellow_1	#99884c
yellow_2	#eeee9e
green_1	#558855
green_2	#a8cca8
green_3	#eaffea
cyan_1	#5aaaaa
cyan_2	#8ccccc
cyan_3	#9eeeee
cyan_4	#eaffff
blue_1	#4670bb
blue_2	#afdbff
blue_3	#cbe7ff
blue_4	#ebf5ff
purple_1	#8888cc
purple_2	#bbbbff
magenta_1	#aa6688
magenta_2	#d08eaa

border_1	#00000058
border_2	#000000cc
invisible	#00000000
