#!/usr/bin/env python3

colors = {
    "paleyellow_1": "#ffffee",
    "paleyellow_2": "#f2f2e2",
    "paleyellow_3": "#eeeede",
    "paleyellow_4": "#777770",
    "gray_1": "#f6f6f6",
    "gray_2": "#eeeeee",
    "gray_3": "#e8e8e8",
    "gray_4": "#888888",
    "black": "#000000",
    "white": "#ffffff",
    "red_1": "#bb5d5d",
    "red_2": "#dd8888",
    "orange_1": "#c78f67",
    "orange_2": "#f8dfc8",
    "yellow_1": "#99884c",
    "yellow_2": "#eeee9e",
    "green_1": "#558855",
    "green_2": "#a8cca8",
    "green_3": "#eeffee",
    "cyan_1": "#5aaaaa",
    "cyan_2": "#8ccccc",
    "cyan_3": "#aeeeee",
    "cyan_4": "#eeffff",
    "blue_1": "#4670bb",
    "blue_2": "#afdbff",
    "blue_3": "#cbe7ff",
    "blue_4": "#ebf5ff",
    "purple_1": "#8888cc",
    "purple_2": "#bbbbff",
    "magenta_1": "#aa6688",
    "magenta_2": "#d08eaa",
    "border_1": "#00000058",
    "border_2": "#000000cc",
    "invisible": "#00000000",
}

base = {
    **colors,
    "type": "light",
    "blank_bg": colors["white"],
    "popup_bg": colors["white"],
    "fg": colors["black"],
    "fg_dim": colors["black"] + "78",
    "fg_faint": colors["black"] + "40",
    "fg_ghost": colors["black"] + "20",
    "neutral_hl": colors["black"] + "10",
    "badge_bg": colors["purple_1"],
    "badge_fg": colors["white"],
    "button_bg": colors["purple_1"],
    "button_fg": colors["white"],
}

themes = [
    {
        **base,
        "name": "Acme",
        "bg_1": colors["paleyellow_1"],
        "bg_2": colors["paleyellow_2"],
        "bg_3": colors["paleyellow_3"],
        "ui_bg": colors["cyan_4"],
        "ui_hl": colors["cyan_3"],
        "match_bg": colors["yellow_2"] + "ee",
        "match_focus_bg": colors["purple_2"] + "aa",
        "selection_bg": colors["yellow_2"] + "ee",
        "gray": colors["paleyellow_4"],
    },
    {
        **base,
        "name": "Acme White",
        "bg_1": colors["white"],
        "bg_2": colors["gray_1"],
        "bg_3": colors["gray_2"],
        "ui_bg": colors["blue_4"],
        "ui_hl": colors["blue_2"],
        "match_bg": colors["orange_2"] + "ee",
        "match_focus_bg": colors["blue_3"] + "ee",
        "selection_bg": colors["gray_3"],
        "gray": colors["gray_4"],
        "yellow_2": colors["orange_2"],
    },
]

